#!/bin/sh
dest="/Users/ashleycoleman/Dropbox/_PROJECTS/portfolio/testdeploy" #keep the quotes
for i in `cat < list.txt` #loop each line of list.txt
do
cp $i $dest #in each loop copy $i, e/a line of list.txt to $dest
echo "Done."
done
